language: objective-c
osx_image: xcode7
xcode_project: SyncApp.xcodeproj
xcode_scheme: SyncApp
xcode_sdk: iphonesimulator

notifications:
  irc: "irc.freenode.org#feedhenry"

branches:
  only:
    - master